version: '3.7'

services:
  mongodb:
    env_file: .env
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mongo-nest
      - MONGO_INITDB_ROOT_USERNAME=DATABASE_USER
      - MONGO_INITDB_ROOT_PASSWORD=DATABASE_PASSWORD
    ports:
      - 27018:27018
